config/routes.rb
Rails.application.routes.draw do
  
  resources :selected_tasks
  resources :instructions
  
  resources :patients do
  	resources :instructions
  end

  root :to => "task_lists#index"

  resources :task_lists do
  	resources :task_items 
	end

	resources :task_items
  post 'item_archive/:id' => 'task_items#archive'
  post 'list_archive/:id' => 'task_lists#archive'

  get 'update_selected_task/:id' => 'instructions#update_selected_task'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instruction.rb
class Instruction < ApplicationRecord
	belongs_to :patient
	belongs_to :task_list

	has_many :selected_tasks, :dependent => :destroy

	accepts_nested_attributes_for :selected_tasks
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]
  before_action :set_patient, only: [:new, :edit]
  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = Instruction.all
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    # get tasks lists to display possible choices of task items to select
    @task_lists = TaskList.where("archive = ? OR archive IS NULL", "false")
    
    @instruction = Instruction.new

    @html_content = render_to_string :partial => 'instructions/form', :locals => { task_lists: @task_lists, instruction: @instruction, patient: @patient, button_text: "Assign" }
    
    # send html to javascript to insert the form html into the modal
    render :json => { :html_content => @html_content, title: "Assign Task List" }
  end

  # GET /instructions/1/edit
  def edit
    # sort tasks by due date
    @selected_tasks = @instruction.selected_tasks

    # more preferable to use active record order, in the future add the due attr to the selected tasks
    @selected_tasks = @selected_tasks.sort_by { |st| st.task_item.due }

    if @selected_tasks.all? { |st| st.is_complete }
      # when viewing tasks from the patient list and all tasks are complete
      @html_content = render_to_string :partial => 'instructions/instructions_complete', :locals => { selected_tasks: @selected_tasks, instruction: @instruction, patient: @patient, button_text: nil }
      
      render :json => { :html_content => @html_content, title: "Congratulations!" }    
    else
      # displaying task items for a patient so that they may interact with them
      @html_content = render_to_string :partial => 'instructions/patient_task_list', :locals => { selected_tasks: @selected_tasks, instruction: @instruction, patient: @patient, button_text: nil }

      title = "Task List for #{@patient.first_name} #{@patient.last_name}"

      render :json => { :html_content => @html_content, title: title }
    end
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    # build the selected tasks based off of the selected task_items
    # could be done better with nested form attributes
    task_item_ids = params[:selected_tasks].keys

    task_item_ids.size.times { |idx| @instruction.selected_tasks.build(task_item_id: task_item_ids[idx]) }

    # on successful save, return to patients index
    # not currently handling saving errors
    respond_to do |format|
      if @instruction.save
        @patients = Patient.all
        format.html { render "patients/index", notice: 'Instruction was successfully created.' }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to @instruction, notice: 'Instruction was successfully updated.' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_selected_task
    # :instruction_id, :task_item_id, :is_complete, :complete_date
    selected_task_id = params[:id]

    @selected_task = SelectedTask.find(selected_task_id)

    @selected_task.update(is_complete: true, complete_date: Time.now)
    
    # check if all task are complete, if so, send back new html
    if @selected_task.instruction.selected_tasks.all? { |st| st.is_complete == true }
      # return new html
      @html_content = render_to_string :partial => 'instructions/instructions_complete', :locals => { button_text: nil }

      render :json => { :html_content => @html_content, title: "Congratulations!" }
    else
      # return the object as json to update the modal
      render :json => { selected_task: @selected_task }
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to instructions_url, notice: 'Instruction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    # Only allow a list of trusted parameters through.
    def instruction_params
      params.require(:instruction).permit(
        :task_list_id, :patient_id, :start_date,
        selected_tasks_attributes: [:task_item_id, :instruction_id, :is_complete, :complete_date])
    end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_form.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <%= form_with(model: instruction, local: true) do |form| %>
      <% if instruction.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

          <ul>
            <% instruction.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <select class="form-control" id="select-task-list">
          <option value="">Select a Task List</option>
        <% task_lists.each do |task_list| %>
          <option value="<%= task_list.id %>">
            <%= task_list.name %>
          </option>
        <% end %>
      </select>
      <br>
      <div style="height: 200px">
        <h6 id="include-items" style="display:none;">Include Items</h6>
        
        <table class="table">
          <thead></thead>
          <tbody>
        
            <% task_lists.each do |task_list| %>
              <% task_list.task_items.where("archive = ? OR archive IS NULL", "false").each do |task_item| %>
                <tr>
                  <div class="form-check task-list-<%= task_list.id %>" style="display:none;">
                    <%= check_box :selected_tasks, "#{task_item.id}", { class: "form-check-input" }, true, false %>
                    <%= form.label task_item.title, class: "form-check-label" %>
                  </div>
                </tr>
              <% end %>
            <% end %>

          </tbody>
        </table>
          
        <%= form.hidden_field :patient_id, :value => patient.id %>
        <%= form.hidden_field :task_list_id, :value => '' %>

        <div class="form-group" id="instructions-date" style="display:none;" >
          <%= form.label :start_date %>
          <% default = DateTime.now %>
          <%= form.date_select :start_date, default: default %>
        </div>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit button_text, :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/instructions/_instructions_complete.html.erb
<h6 style="text-align: center;">
	You have completed all your tasks!
</h6>
<button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Ok</button>

app/views/instructions/_patient_task_list.html.erb
<div class="row">
  <div class="col-md-10 mx-auto">
  	<!-- list the selected tasks -->
  	<!-- display the due date -->
  	<!-- each has a check box which updates is_complete -->
  	<!-- on update display completed on date -->
  	<!-- drop down to show (reveal on carrot click) all html text from selected_task.task_item.body -->
  	<table class="table">
  		<thead></thead>
  		<tbody>
  			<!-- sort tasks by due date -->
  			<% selected_tasks.each do | selected_task | %>
  				<div class="card">
  					<div class="card-header">
							<label style="display: inline;">
								<%= check_box_tag :selected_task, selected_task.id, selected_task.is_complete, { class: "selected-task", disabled: selected_task.is_complete} %> 
								<%= selected_task.task_item.title %>
							</label>
							<% if selected_task.is_complete == true %>
								<!-- display completed_on -->
								<i id="task-item-due-<%= selected_task.id %>">
									Completed: <%= selected_task.complete_date %>
								</i>
							<% else %>
								<!-- display due date -->
								<% due_date = instruction.start_date + selected_task.task_item.due %>
								<i id="task-item-due-<%= selected_task.id %>">
									Due: <%= due_date %> 
								</i> 
								
								<% if due_date < DateTime.now %>
										<p id="task-due-warning" style="display: inline-block;">&#9888;</p>
								<% else %>
										<p id="task-due-warning" style="display: inline-block;"></p>
								<% end %>
									

							<% end %>
						  
						  <button type="button" class="display-task-item-body float-right" data-toggle="collapse" data-target="#task-item-body-<%= selected_task.id %>" aria-expanded="false" aria-controls="task-item-body-<%= selected_task.id %>">&#9650;</button>
						</div>
					  
					  <div class="collapse" id="task-item-body-<%= selected_task.id %>">
						  <div class="card card-body">
						  	<% html = selected_task.task_item.body %>
						    <%= sanitize html %>
						  </div>
						</div>

					  </div>
  				</div>
  				<br>
	  				
  			<% end %>

  		</tbody>
  	</table>
  </div>
</div>

app/views/instructions/edit.html.erb
<h1>Editing Instruction</h1>

<%= render 'form', instruction: @instruction %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructions</h1>

<table>
  <thead>
    <tr>
      <th>Task list</th>
      <th>Patient</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructions.each do |instruction| %>
      <tr>
        <td><%= instruction.task_list_id %></td>
        <td><%= instruction.patient_id %></td>
        <td><%= instruction.start_date %></td>
        <td><%= link_to 'Show', instruction %></td>
        <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
        <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New Instruction</h1>

<%= render 'form', instruction: @instruction %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task list:</strong>
  <%= @instruction.task_list_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @instruction.patient_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @instruction.start_date %>
</p>

<%= link_to 'Edit', edit_instruction_path(@instruction) %> |
<%= link_to 'Back', instructions_path %>