config/routes.rb
Rails.application.routes.draw do
  
  resources :selected_tasks
  resources :instructions
  
  resources :patients do
  	resources :instructions
  end

  root :to => "task_lists#index"

  resources :task_lists do
  	resources :task_items 
	end

	resources :task_items
  post 'item_archive/:id' => 'task_items#archive'
  post 'list_archive/:id' => 'task_lists#archive'

  get 'update_selected_task/:id' => 'instructions#update_selected_task'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task_item.rb
class TaskItem < ApplicationRecord
  belongs_to :task_list
end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController
  before_action :set_task_item, only: [:show, :edit, :update, :destroy, :archive]
  before_action :set_task_list, only: [:index, :new, :edit]
  # GET /task_items
  # GET /task_items.json
  def index
    @task_items = @task_list.task_items
  end

  # GET /task_items/1
  # GET /task_items/1.json
  def show
  end

  # GET /task_items/new
  def new
    @task_item = @task_list.task_items.build

    @html_content = render_to_string :partial => 'task_items/form', :locals => { task_item: @task_item, task_list: @task_list, button_text: "Add" }
    
    render :json => { :html_content => @html_content, title: "New Task Item" }
  end

  # GET /task_items/1/edit
  def edit

    @html_content = render_to_string :partial => 'task_items/form', :locals => { task_item: @task_item, task_list: @task_list, button_text: "Edit" }
    
    render :json => { :html_content => @html_content, title: "Edit Task Item" }
  end

  # POST /task_items
  # POST /task_items.json
  def create
    @task_item = TaskItem.new(task_item_params)

    respond_to do |format|
      if @task_item.save
        
        @task_list = @task_item.task_list
        @task_items = @task_list.task_items 
        
        format.html { render :index, notice: 'Task item was successfully created.' }
        format.json { render :show, status: :created, location: @task_item }
      else
        format.html { render :new }
        format.json { render json: @task_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_items/1
  # PATCH/PUT /task_items/1.json
  def update
    @task_list = @task_item.task_list

    # redirect to the same task list task items
    url = "/task_lists/#{@task_list.id}/task_items"

    respond_to do |format|
      if @task_item.update(task_item_params)
        format.html { redirect_to url, notice: 'Task item was successfully updated.' }
      end
    end
  end

  # DELETE /task_items/1
  # DELETE /task_items/1.json
  def destroy
    @task_item.destroy
    respond_to do |format|
      format.html { redirect_to task_items_url, notice: 'Task item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
    archive_val = @task_item.archive == true ? false : true

    archive_message = archive_val == true ? "#{@task_item.title} has been archived." : "#{@task_item.title} has been removed from the archive."
    
    respond_to do |format|
      if @task_item.update(archive: archive_val)        
        @task_list = @task_item.task_list
        @task_items = @task_list.task_items

        format.html { render :index, notice: archive_message }
      else
        format.html { redirect_to task_lists_url, notice: 'Error archiving.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_item
      @task_item = TaskItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_item_params
      params.require(:task_item).permit(:title, :body, :due, :task_list_id, :archive)
    end

    def set_task_list
      @task_list = TaskList.find(params[:task_list_id])
    end
end

app/helpers/task_items_helper.rb
module TaskItemsHelper

end

app/views/task_items/_form.html.erb
<%= form_with(model: task_item, local: true) do |form| %>
  <% if task_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_item.errors.count, "error") %> prohibited this task_item from being saved:</h2>

      <ul>
        <% task_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :due %>
    <%= form.number_field :due %>
  </div>
  
  <%= form.hidden_field :task_list_id, :value => task_item.task_list_id %>
  
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= form.submit button_text, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/task_items/edit.html.erb
<h1>Editing Task Item</h1>

<%= render 'form', task_item: @task_item %>

<%= link_to 'Show', @task_item %> |
<%= link_to 'Back', task_items_path %>

app/views/task_items/index.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">

    <p id="notice"><%= notice %></p>

    <h1><%= @task_list.name %> Items</h1>

    <table class="table">
      <thead>
      </thead>

      <tbody>
        <% @task_items.each do |task_item| %>
          <tr>
            <% if task_item.archive == true %>
              <td><i><%= task_item.title %></i></td>
            <% else %>
              <td><%= task_item.title %></td>
            <% end %>
            
            <td><a class="task-item-edit" href="/task_lists/<%= task_item.task_list.id %>/task_items/<%= task_item.id %>/edit">edit</a></td>
                                                
            <% archive_item_text = task_item.archive == true ? 'unarchive' : 'archive' %>
            <td><%= link_to archive_item_text, "/item_archive/#{task_item.id.to_s}", method: :post %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <button type="button" class="btn btn-primary" id="add-task-item" href="/task_lists/<%= @task_list.id %>/task_items/new">
      Add Task Item                                                       
    </button>
    <br>
    &larrhk;
    <%= link_to "Task Lists", task_lists_path %>
    <br>
    &larrhk;
    <%= link_to "Patients", patients_path %>
  </div>
</div>

app/views/task_items/new.html.erb
<h1>New Task Item</h1>

<%= render 'form', task_item: @task_item %>

<%= link_to 'Back', task_items_path %>

app/views/task_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task_item.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task_item.body %>
</p>

<p>
  <strong>Due:</strong>
  <%= @task_item.due %>
</p>

<p>
  <strong>Task list:</strong>
  <%= @task_item.task_list_id %>
</p>

<%= link_to 'Back', "/task_lists/#{@task_item.task_list.id}/task_items" %>