config/routes.rb
Rails.application.routes.draw do
  
  resources :selected_tasks
  resources :instructions
  
  resources :patients do
  	resources :instructions
  end

  root :to => "task_lists#index"

  resources :task_lists do
  	resources :task_items 
	end

	resources :task_items
  post 'item_archive/:id' => 'task_items#archive'
  post 'list_archive/:id' => 'task_lists#archive'

  get 'update_selected_task/:id' => 'instructions#update_selected_task'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task_list.rb
class TaskList < ApplicationRecord
	has_many :task_items, :dependent => :destroy
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  include ApplicationHelper
  before_action :set_task_list, only: [:show, :edit, :update, :destroy, :archive, :task_items]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new

    @html_content = render_to_string :partial => 'task_lists/form', :locals => { task_list: @task_list, button_text: "Add" }
    
    render :json => { :html_content => @html_content, title: "New Task List" }
  end

  # GET /task_lists/1/edit
  def edit

    @html_content = render_to_string :partial => 'task_lists/form', :locals => { task_list: @task_list, button_text: "Edit" }
    
    render :json => { :html_content => @html_content, title: "Edit Task List" }
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        @task_lists = TaskList.all
        format.html { render :index, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        @task_lists = TaskList.all
        format.html { render :index, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
    archive_val = @task_list.archive == true ? false : true

    archive_message = archive_val == true ? "#{@task_list.name} has been archived." : "#{@task_list.name} has been removed from the archive."
    
    respond_to do |format|
      if @task_list.update(archive: archive_val)        
        format.html { redirect_to task_lists_url, notice: archive_message }
      else
        format.html { redirect_to task_lists_url, notice: 'Error archiving.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:name, :archive)
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list, local: true) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
        <% task_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= form.submit button_text, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <p id="notice"><%= notice %></p>

    <h1>Template Task Lists</h1>

    <table class="table">
      <thead>
      </thead>

      <tbody>
        <% @task_lists.each do |task_list| %>

          <tr>
            <% if task_list.archive == true %>
              <td><i><%= task_list.name %></i></td>
            <% else %>
              <td><%= task_list.name %></td>
            <% end %>
            
            <td><a class="task-list-edit" href="/task_lists/<%= task_list.id %>/edit">edit</a></td>
            
            <td><a class="task-list-items" href="/task_lists/<%= task_list.id %>/task_items">items</a></td>

            <% archive_link_text = task_list.archive == true ? 'unarchive' : 'archive' %>
            <td><%= link_to archive_link_text, "/list_archive/#{task_list.id.to_s}", method: :post %></td>

          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    
    <button type="button" class="btn btn-primary" id="add-task-list" href="/task_lists/new">
      Add Task List
    </button>
    <br>
    &larrhk;
    <%= link_to "Patients", patients_path %>
  </div>
</div>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_list.name %>
</p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>