config/routes.rb
Rails.application.routes.draw do
  
  resources :selected_tasks
  resources :instructions
  
  resources :patients do
  	resources :instructions
  end

  root :to => "task_lists#index"

  resources :task_lists do
  	resources :task_items 
	end

	resources :task_items
  post 'item_archive/:id' => 'task_items#archive'
  post 'list_archive/:id' => 'task_lists#archive'

  get 'update_selected_task/:id' => 'instructions#update_selected_task'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/selected_task.rb
class SelectedTask < ApplicationRecord
  belongs_to :instruction
  belongs_to :task_item
end

app/controllers/selected_tasks_controller.rb
class SelectedTasksController < ApplicationController
  before_action :set_selected_task, only: [:show, :edit, :update, :destroy]

  # GET /selected_tasks
  # GET /selected_tasks.json
  def index
    @selected_tasks = SelectedTask.all
  end

  # GET /selected_tasks/1
  # GET /selected_tasks/1.json
  def show
  end

  # GET /selected_tasks/new
  def new
    @selected_task = SelectedTask.new
  end

  # GET /selected_tasks/1/edit
  def edit
  end

  # POST /selected_tasks
  # POST /selected_tasks.json
  def create
    @selected_task = SelectedTask.new(selected_task_params)

    respond_to do |format|
      if @selected_task.save
        format.html { redirect_to @selected_task, notice: 'Selected task was successfully created.' }
        format.json { render :show, status: :created, location: @selected_task }
      else
        format.html { render :new }
        format.json { render json: @selected_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selected_tasks/1
  # PATCH/PUT /selected_tasks/1.json
  def update
    respond_to do |format|
      if @selected_task.update(selected_task_params)
        format.html { redirect_to @selected_task, notice: 'Selected task was successfully updated.' }
        format.json { render :show, status: :ok, location: @selected_task }
      else
        format.html { render :edit }
        format.json { render json: @selected_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_tasks/1
  # DELETE /selected_tasks/1.json
  def destroy
    @selected_task.destroy
    respond_to do |format|
      format.html { redirect_to selected_tasks_url, notice: 'Selected task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_task
      @selected_task = SelectedTask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def selected_task_params
      params.require(:selected_task).permit(:instruction_id, :task_item_id, :is_complete, :complete_date)
    end
end

app/helpers/selected_tasks_helper.rb
module SelectedTasksHelper
end

app/views/selected_tasks/_form.html.erb
<%= form_with(model: selected_task, local: true) do |form| %>
  <% if selected_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(selected_task.errors.count, "error") %> prohibited this selected_task from being saved:</h2>

      <ul>
        <% selected_task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :instruction_id %>
    <%= form.text_field :instruction_id %>
  </div>

  <div class="field">
    <%= form.label :task_item_id %>
    <%= form.text_field :task_item_id %>
  </div>

  <div class="field">
    <%= form.label :is_complete %>
    <%= form.check_box :is_complete %>
  </div>

  <div class="field">
    <%= form.label :complete_date %>
    <%= form.date_select :complete_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/selected_tasks/edit.html.erb
<h1>Editing Selected Task</h1>

<%= render 'form', selected_task: @selected_task %>

<%= link_to 'Show', @selected_task %> |
<%= link_to 'Back', selected_tasks_path %>

app/views/selected_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selected Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Instruction</th>
      <th>Task item</th>
      <th>Is complete</th>
      <th>Complete date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selected_tasks.each do |selected_task| %>
      <tr>
        <td><%= selected_task.instruction_id %></td>
        <td><%= selected_task.task_item_id %></td>
        <td><%= selected_task.is_complete %></td>
        <td><%= selected_task.complete_date %></td>
        <td><%= link_to 'Show', selected_task %></td>
        <td><%= link_to 'Edit', edit_selected_task_path(selected_task) %></td>
        <td><%= link_to 'Destroy', selected_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selected Task', new_selected_task_path %>

app/views/selected_tasks/new.html.erb
<h1>New Selected Task</h1>

<%= render 'form', selected_task: @selected_task %>

<%= link_to 'Back', selected_tasks_path %>

app/views/selected_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instruction:</strong>
  <%= @selected_task.instruction_id %>
</p>

<p>
  <strong>Task item:</strong>
  <%= @selected_task.task_item_id %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @selected_task.is_complete %>
</p>

<p>
  <strong>Complete date:</strong>
  <%= @selected_task.complete_date %>
</p>

<%= link_to 'Edit', edit_selected_task_path(@selected_task) %> |
<%= link_to 'Back', selected_tasks_path %>